---
title: "LOESS analysis"
author: "Jordana Bloom"
date: "2024-12-01"
output: html_document
---

Adapted from Piehl et al. 2022

Load files and define parameters

```{r}
# Load in libraries
suppressMessages({
  library("plyr")
  library("tidyverse")
  library("ggrepel")
  library("ggthemes")
  library("ggpubr")
  #library("Seurat")
  library("factoextra")
  library("scales")
  library("patchwork")
  library("clusterProfiler")
  library("pheatmap")
  library("colorspace")
})

  library(base)
`%!in%` <- Negate(`%in%`)

sessionInfo()

# Initialize paths
output_parent_dir <- "/your/directory/path/"

# Generate output directory
dir.create(output_parent_dir, showWarnings = FALSE, recursive = TRUE)

#Load files
##use supplemental data table S6
data <- read.delim("supplementalTableS6.txt", header=TRUE, check.names=FALSE)
# Set the row names  
row_names <- make.unique(as.character(data$gene_id))
rownames(data) <- row_names

##supplemental data table S1 includes sample IDs, exact age is protected data; but age ranges are available at https://gtexportal.org/home/ 
meta <- read.delim("supplementalTableS1.txt", header=TRUE, check.names = FALSE, row.names = 1)
    
filt = data$gene.type == "protein_coding"
data2 <- data[filt,]
dim(data2)

gene_id <- as.data.frame(data2$gene_id)
row_names <- make.unique(as.character(data2$gene_id))
rownames(data2) <- row_names

# Remove the last gene.type column
data2 <- data2[, -c(ncol(data2))]
data <- data2

#add a puesdocount of 0.1 to all values in the dataframe
data[,-1] <- data[,-1] + 0.1

#take log2 of values in the dataframe
data[,-1] <- lapply(data[,-1], function(x) log2(x))

#calculate z score of each row in the dataframe
data[,-1] <- apply(data[,-1], 1, scale)

data2 <- as.data.frame(t(data), header=FALSE)
colnames(data2) <- data2[1,]
data2 <- data2[-1, ]

data3 <- as.data.frame(t(data), header=FALSE)
colnames(data3) <- data3[1,]
data3 <- data3[-1, ] 
head(data3)
data2[is.na(data2)] = 0
data2 <- lapply(data2,as.numeric)
    
data2 <- as.data.frame(data2, header=TRUE, check.names=FALSE)
row.names(data2) <- row.names(data3)
head(data2)
rownames(data2) <- make.names(rownames(data2), unique = TRUE)
data2 <- data2[, !duplicated(names(data2))]
data2 <- rownames_to_column(data2, var="gene.names")

# Checking duplicate row names
duplicated_rows <- data2[duplicated(rownames(data2)), ]
print("Duplicate rows:")
print(duplicated_rows)

# Get the column names
column_names <- names(data2)

#filters for particular genes, if interested in selecting specific genes
#data2 <- data2 %>% select(c('gene.names','TAC1','KISS1', 'TACR3', 'PDYN','KISS1R','TAC3'))

meta <- select(meta, SAMPID, AGE, Tissue)
names(meta)[names(meta) == "SAMPID"] <- "ID"

# Convert periods to hyphens in the first column
data2$gene.names <- gsub("\\.", "-", data2$gene.names)

scatter_DF <- merge(data2, meta, by.x= "gene.names", by.y="ID", all.x = TRUE)
names(scatter_DF)[1] = "ID"
data <- scatter_DF

# Define number of clusters to generate
cluster_nums = 13:24

Tissue <- "Brain - Hypothalamus"

# desired age range
age_min <- 28
age_max <- 65

# Define non-gene column names
non_gene_cols <- c("ID", "AGE", "Tissue")

```

Run Analysis

```{r}
data_subset <- subset_data(data,Tissue)

execute_on_celltype(data, Tissue, output_parent_dir)


main <- function() {
  # Load data
  #load(data_path)
  #print(head(data[,1:10]))
  
 # Run LOESS
  if (length(Tissue) != 1) {
    for (type in Tissue) {
      execute_on_celltype(data, Tissue, output_parent_dir)
    }
 # } else if (cell_type != "allandcelltype") {
  #  execute_on_celltype(data, AGE, Tissue, output_parent_dir)
  } else {
    #if (clonal == "Hypothalamus") {
      for (type in unique(data$Tissue)) {
        print(paste0("Analyzing ", type))
        execute_on_celltype(data, Tissue, output_parent_dir)
      }
    #} else {
     # for (type in c("Hypothalamus")) {
      #  print(paste0("Analyzing ", type))
       # execute_on_celltype(data, AGE, Tissue, output_parent_dir)
      }
    } 
 # }
#}

main()
```


```{r}
execute_on_celltype <- function(data, Tissue, output_parent_dir) {
  # Generate cell_type label for naming
  Tissue_label <- gsub("/","", Tissue)
  
  # Define cell_type output dir
  output_dir <- file.path(output_parent_dir, Tissue_label)
  dir.create(output_dir, showWarnings = FALSE)
  
  # Choose features of interest
  #load(Tissue_label, "_over10_genes")
  #genes <- over10_genes
  #names(data) <- gsub("-", ".", names(data))
  #genes <- gsub("-", ".", genes)
  
  # Subset based on clonal, diagnosis, and sex
  data_subset
  
  # Scale genes
  data_scaled <- data_subset
  data_scaled <- data_scaled %>% select(-c(Tissue, ID))
  data_scaled[ ,(names(data_scaled) %!in% non_gene_cols)] <- scale(data_scaled[ ,(names(data_scaled) %!in% non_gene_cols)])
  data_scaled$AGE <- as.numeric(as.character(data_scaled$AGE))
  data_scaled[ ,(names(data_scaled) %!in% non_gene_cols)] <- data_scaled[ ,(names(data_scaled) %!in% non_gene_cols)][ , colSums(is.na(data_scaled[ ,(names(data_scaled) %!in% non_gene_cols)])) == 0]

  # Reassign genes
 genes <- names(data)
 genes <- genes[ genes %!in% non_gene_cols ]
  
  if (length(grep("compare", c(Tissue))) == 0) {
    # Run LOESS on all genes
     lo_predict_list <- lapply(genes, run_loess, data = data)
    
    # Merge lo_predict
    lo_predict <- as.data.frame(lo_predict_list)
    lo_predict$AGE <- seq(age_min, age_max, 1)
    lo_predict <- dplyr::relocate(lo_predict, AGE)
    
    # Generate heatmap of lo_predict, if not comparing
    heatmap_of_loess(lo_predict, output_dir, Tissue_label)
    
    # Generate clusters of lo_predict and plot data of clusters with regression
    cluster_loess(lo_predict = lo_predict, data = data,
                  output_dir = output_dir, Tissue_label = Tissue_label,
                  cluster_nums = cluster_nums)
    
    # Export lo_predict
    write.csv(lo_predict, paste0(Tissue_label, "_lo_predict.csv"))
  } else {
    # Load HC data for gene clusters
   hclust_cut_merged <- read.csv(ref_clustering, "/", Tissue_label, "/", Tissue_label, "_hclust_cut.csv", row.names = 1)
    
    # Generate clusters of data using HC clusters
    cluster_loess(hclust_cut_merged = hclust_cut_merged, data = data,
                 output_dir = output_dir, Tissue_label = Tissue_label,
                  cluster_nums = cluster_nums)
  }
  # Export data scaled
  write.csv(data, paste0(output_dir, "/", "_data.csv"))
}
```

Define functions

```{r}

cluster_loess <- function(data_scaled, output_dir, Tissue_label,
                          cluster_nums = cluster_nums, lo_predict = NULL, hclust_cut_merged = NULL) {
  # If not performing comparison
  if (!is.null(lo_predict)) {
    # Perform distance calculation on all trajectories (removing age column)
    dist_mat <- dist(t(lo_predict[,2:ncol(lo_predict)]))
    
    # Plot hierarchal clusters
    pdf(paste0(Tissue, "_dendogram_loess_predicted.pdf"))
    clust <- hclust(dist_mat, method = "complete")
    plot(clust, labels = FALSE)
    dev.off()
    
    # Initialize hclust_cut_list
    hclust_cut_list <- list()
  }
  
  # Generate clustering with k = cluster_nums
  for (k in cluster_nums) {
     # Check if we have enough genes
    if (!is.null(lo_predict)) {
      if (k > (ncol(lo_predict) - 1)) {
        print(paste0("Insufficient gene number for ", k, " clusters"))
        next
      }
      
      # Generate hierarchical clusters
      hclust_cut <- data.frame(cutree(clust, k = k))
    } else {
      # Isolate hierarchical clusters
     hclust_cut <- hclust_cut_merged[,match(k, cluster_nums),drop = FALSE]
    }

    # Generate color vector
    color_vector <- hue_pal()(k)
    
    # Initialize plot list
    hclust_plot_list <- list()
    
    for (i in seq(k)) {
      # Subset genes of interest
      cols <- c(rownames(hclust_cut[ which(hclust_cut[,1] == i), ,drop = FALSE]), "AGE")
      colnames_df <- colnames(data_scaled)
      cols <- intersect(colnames_df, cols)
      data_scaled_subset <- data_scaled[, cols]

      if (!is.null(lo_predict)) {
        data_long <- gather(data_scaled_subset, genes, expression, -AGE)
        data_long <- data_long[!data_long$genes=="ID",]
        data_long <- data_long[!data_long$genes=="Tissue",]
        #min_val <- min(data_long$expression)
        #max_val <- max(data_long$expression)
        
        # Run plotting
        plot <- line_plot_of_loess(data_long, color = color_vector[i])
       # print(plot)
      } 
       # Append plot to list
      hclust_plot_list[[i]] <- plot
    }
  
    # Generate figure of clustered trajectories
    if (k == 1) {
      pdf(paste0(Tissue, "_hclust_k", k, ".pdf"))
      print(hclust_plot_list[[1]])
      dev.off()
    } else {
      patchwork <- wrap_plots(hclust_plot_list, guides = "collect")
      if (is.null(lo_predict)) {
        patchwork <- patchwork + plot_annotation(subtitle = paste0(Tissue, ": gray = ", group1, ", color = ", group2))
      } else {
        patchwork <- patchwork + plot_annotation(subtitle = Tissue)
      }
      pdf(paste0(Tissue, "_hclust_k", k, ".pdf"))
      print(patchwork)
      dev.off()
    }
    
    # Append cut to list
    if (!is.null(lo_predict)) {hclust_cut_list[[k]] <- hclust_cut}
  }
  # Write out cluster cut
  if (!is.null(lo_predict)) {
    hclust_cut_merged <- as.data.frame(do.call(cbind, hclust_cut_list[cluster_nums]))
    write.csv(hclust_cut_merged, file = paste0(Tissue, "_hclust_cut.csv"))
  }
}

```


```{r}
# Define publication theme plotting function
theme_Publication_blank <- function(base_size=12, base_family="") {
  (theme_foundation(base_size=base_size, base_family=base_family)
   + theme(plot.title = element_text(size = rel(1.2), hjust = 0.5),
           text = element_text(),
           panel.background = element_rect(fill = "transparent",colour = NA),
           plot.background = element_rect(fill = "transparent",colour = NA),
           panel.border = element_rect(colour = NA, fill = "transparent"),
           axis.title = element_text(size = rel(1)),
           axis.title.y = element_text(angle=90,margin=margin(0,10,0,0)),
           axis.title.x = element_text(margin=margin(10,0,0,0)),
           axis.text = element_text(), 
           axis.line = element_line(colour="black"),
           axis.ticks = element_line(size = 0.3),
           axis.line.x = element_line(size = 0.3, linetype = "solid", colour = "black"),
           axis.line.y = element_line(size = 0.3, linetype = "solid", colour = "black"),
           panel.grid.major = element_blank(),
           panel.grid.minor = element_blank(),
           legend.key = element_rect(colour = NA, fill="transparent"),
           legend.position = "bottom",
           legend.margin = margin(t = 10, unit='pt'),
           plot.margin=unit(c(10,5,5,5),"mm"),
           strip.background=element_rect(colour="#d8d8d8",fill="#d8d8d8")
   ))
} 

subset_parameters <- function(data, param) {
  # Select for param settings
  group <- deparse(substitute(param))
   if (group == "Tissue") {
      data <- data[ which(data[,group] == param), ]
    }
} 

subset_data <- function(data, Tissue) {
  genes <- names(data)
  genes <- genes[ genes %!in% non_gene_cols ]
  # Subset based on features
  if (!is.null(genes)) {
    data <- data[ ,c(genes, non_gene_cols)]
    if ((ncol(data) - length(non_gene_cols)) == length(genes)) {
      print(paste0("Successfully selected for ", length(genes), " feature(s)"))
    }
  }
  
  # Subset based on parameters
  data <- subset_parameters(data, Tissue)
  
  # Subset based on age range
  data <- data[which(data$AGE %in% seq(age_min, age_max)),]
}

run_loess <- function(genes, data) {
  # Extract gene specific data
  data <- data[ ,c(genes, non_gene_cols)]
  
  # Generate LOESS model and save to lo_data
  lo <- loess(get(genes) ~ AGE, data, span = 0.75)
  
  # Generate predicted values
  lo_predict <- predict(lo, data.frame(AGE = seq(age_min, age_max, 1))) %>%
    # lo_predict <- predict(lo, data.frame(age = seq(age_min, age_max, 0.0833))) %>%
    as.data.frame()
  colnames(lo_predict) <- genes
  
  return(lo_predict)
}

heatmap_of_loess <- function(lo_predict, output_dir, Tissue_label) {
  # Convert wide to long
  lo_predict_long <- gather(lo_predict, genes, expression, 2:ncol(lo_predict))
  lo_predict_long2 <- lo_predict_long
  
  #############
  # Order genes by hclustering
  clust_order <- hclust(dist(t(lo_predict[,2:ncol(lo_predict)])))$order
  #col_names <- colnames(lo_predict)[clust_order]
  #clust_order <- match(colnames, unique(lo_predict_long$genes))
  #clust2 <- as.data.frame(clust_order)
  test <- unique(lo_predict_long$genes)[clust_order]
    indices <- c()
    for (value in test) {
      indices <- c(indices, which(lo_predict_long$genes == value))
    }
  # Order the rows of the data frame
    lo_predict_long <- lo_predict_long[indices,]
  
  # Add limits for heatmap plotting
  zscore_limit <- 0.5
  lo_predict_long_plotting <- lo_predict_long
  lo_predict_long_plotting[ which(lo_predict_long_plotting$expression < -zscore_limit), "expression"] <- -zscore_limit
  lo_predict_long_plotting[ which(lo_predict_long_plotting$expression > zscore_limit), "expression"] <- zscore_limit
  
  # Generate heatmap
  p <- ggplot(lo_predict_long_plotting , aes(x = AGE, y = genes, fill = expression)) +
    theme_Publication_blank() +
    geom_raster(interpolate=TRUE) +
    theme(axis.text.y=element_blank()) +
    scale_fill_gradient2(low = "cyan", mid = "black", high = "yellow",
                         breaks = c(-zscore_limit, zscore_limit),
                         limits = c(-zscore_limit, zscore_limit))
  
  # Export heatmap
  ggplot2::ggsave(paste0(Tissue_label, "_loess_predicted_heatmap.pdf"), p, width = 5, height = 4)
}

line_plot_of_loess <- function(data, color, ylim = NULL, data_compare = NULL,
                               alpha = 0.05, size = 0.3, plot_ind_genes = TRUE) {
  # Find average expression over age of all genes in cluster
  #sapply(data_long, class)   
  data$expression <- as.integer(data$expression)
  data[is.na(data)] = 0
  avg <- data %>%
    group_by(AGE) %>%
    summarize_each(funs(mean, sd, se=sd(.)/sqrt(n())), expression)
  
  # Generate LOESS model and save to lo_data
  lo <- loess(mean ~ AGE, avg, span = 0.75)
  lo_predict <- predict(lo, data.frame(AGE = avg$AGE))
  avg <- add_column(avg, lo = lo_predict)
  
  # Define gene number annotation df
  annotations <- data.frame(
    xpos = c(-Inf),
    ypos =  c(Inf),
    annotateText = c(paste0("n=", length(unique(data$genes)))),
    hjustvar = c(-0.5) ,
    vjustvar = c(1))
  
  if (is.null(data_compare)) {
    # Generate plot
    plot <- ggplot(data, aes(x = AGE, y = expression)) +
      theme_Publication_blank() +
      geom_line(stat="smooth", method = "loess", span = 0.75, se = FALSE,
                aes(group = genes),
                alpha = .05, color = color, size = size) +
      scale_y_continuous(expand = c(0,0)) +
      scale_x_continuous(expand = c(0,0)) +
      geom_line(data = avg,
                aes(x = AGE, y = mean),
                stat="smooth", method = "loess", span = 0.75, se = FALSE,
                color = darken(color, amount = 0.3), size = size * 3) +
      theme(legend.position = "none",
            aspect.ratio = 1,
            text = element_text(size = 8),
            panel.spacing = unit(c(0, 0, 0, 0), "null")) +
      geom_text(data=annotations,aes(x=xpos,y=ypos,hjust=hjustvar,vjust=vjustvar,label=annotateText)) +
      {if(!is.null(ylim))ylim(ylim)}
  } else {
    # Find average expression over age of all genes in cluster
    avg_compare <- data_compare %>%
      group_by(AGE) %>%
      summarize_each(funs(mean, sd, se=sd(.)/sqrt(n())), expression)
    
    # Generate LOESS model and save to lo_data
    lo <- loess(mean ~ AGE, avg_compare, span = 0.75)
    lo_predict <- predict(lo, data.frame(AGE = avg_compare$AGE))
    avg_compare <- add_column(avg_compare, lo = lo_predict)
    
    # Find shared age range
    min_age_compare <- max(min(data$AGE), min(data_compare$AGE))
    max_age_compare <- min(max(data$AGE), max(data_compare$AGE))
    
    # Extract regression values
    p_tmp <- ggplot(data, aes(x = AGE, y = expression)) +
      geom_line(data = avg, aes(x = AGE, y = mean),
                stat="smooth", method = "loess", span = 0.75)
    stats <- ggplot_build(p_tmp)$data[[1]][seq(1,80,by=8),]
    
    p_tmp <- ggplot(data_compare, aes(x = AGE, y = expression)) +
      geom_line(data = avg_compare, aes(x = AGE, y = mean),
                stat="smooth", method = "loess", span = 0.75)
    compare_stats <- ggplot_build(p_tmp)$data[[1]][seq(1,80,by=8),]
    
    # Generate plot
    plot <- ggplot(data, aes(x = AGE, y = expression)) +
      theme_Publication_blank() +
      {if(plot_ind_genes)
        geom_line(stat="smooth", method = "loess", span = 0.75, se = FALSE,
                  aes(group = genes),
                  alpha = alpha, color = "gray", size = size)} +
      {if(plot_ind_genes)
        geom_line(data = data_compare,
                  aes(x = AGE, y = expression, group = genes),
                  stat="smooth", method = "loess", span = 0.75, se = FALSE,
                  alpha = alpha, color = color, size = size)} +
      geom_line(data = avg,
                aes(x = AGE, y = mean),
                stat="smooth", method = "loess", span = 0.75, se = FALSE,
                color = "black", size = size * 3) + #gray40
      geom_line(data = avg_compare,
                aes(x = AGE, y = mean),
                stat="smooth", method = "loess", span = 0.75, se = FALSE,
                color = color, size = size * 3) +
      geom_errorbar(inherit.aes = FALSE, data = stats, color = "black",
                    mapping = aes(x = x, ymin = y-se, ymax=y+se), width = 0.5, size = 0.3) +
      geom_errorbar(inherit.aes = FALSE, data = compare_stats, color = color,
                    mapping = aes(x = x, ymin = y-se, ymax=y+se), width = 0.5, size = 0.3) +
      theme(legend.position = "none",
            aspect.ratio = 1,
            text = element_text(size = 8),
            panel.spacing = unit(c(0, 0, 0, 0), "null")) +
      coord_cartesian(xlim=c(min_age_compare, max_age_compare)) +
      geom_text(data=annotations,aes(x=xpos,y=ypos,hjust=hjustvar,vjust=vjustvar,label=annotateText)) +
      {if(!is.null(ylim))ylim(ylim)}
  }
  return(plot)
}
```

